sqs_setup:
    unknownMessageOutUrl: https://sqs.us-west-2.amazonaws.com/XXXXXXX/na-unknownMessageOut-1
    eventMessageOutUrl: https://sqs.us-west-2.amazonaws.com/XXXXXXX/na-eventMessageOut-1
    jbusMessageOutUrl: https://sqs.us-wes-2.amazonaws.com/XXXXXXX/na-idReportMessageOut-1
    idReportMessageOutUrl: https://sqs.us-wes-2.amazonaws.com/XXXXXXX/na-idReportMessageOut-1
    dtcMessageOutUrl: https://sqs.us-west-2.amazonaws.com/XXXXXXX/na-dtcMessageOut-1
    calAmpByteStreamTapUrl: https://sqs.us-west-2.amazonaws.com/XXXXXXX/na-calAmpByteStreamTap-1
    eventMessageOutputTapUrl: https://sqs.us-west-2.amazonaws.com/XXXXXXX/na-eventMessageOutputTap-1
    unknownMessageOutputTapUrl: https://sqs.us-west-2.amazonaws.com/XXXXXXX/na-unknownMessageOutputTap-1
    secondsPerPoll: 2
    awsRegion: us-west-2
    prefetchCount: 65536
